#!/bin/bash
set -e

# Caminho onde o ambiente virtual será criado
VENV_DIR="/opt/handvolume/venv"

# Criar venv se não existir
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
fi

# Ativar e instalar dependências
source "$VENV_DIR/bin/activate"
pip install --upgrade pip
pip install -r /opt/handvolume/requirements.txt

exit 0

